name: flutter_start
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.0.800+340260

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  connectivity: ^0.4.9+3
  event_bus: ^1.1.0
  package_info: ^0.4.0+6
  permission_handler: ^5.0.1
  #  imei_plugin: ^1.1.0
  image_picker: ^0.6.1+2
  #  image_picker: ^0.6.5
  flustars: ^0.3.2
  flutter_spinkit: ^4.1.2+1
  cached_network_image: ^2.2.0+1
  flutter_des: ^1.1.0
  #  image_cropper: ^1.1.0
  flutter_redux: ^0.6.0
  rxdart: ^0.24.1
  uuid: 2.2.0
  path_provider: ^1.2.0
  flutter_swiper: ^1.1.6
  flutter_easyrefresh: ^1.2.7
  tflite: ^1.0.4
  url_launcher: ^5.2.5
  chewie: ^0.9.10
  video_player: ^0.10.12+2
  flutter_audio_recorder: ^0.5.5
  image_gallery_saver: ^1.5.0
  imei_plugin: ^1.1.0
  #  flutter_video_compress: ^0.3.7+8
  video_compress: ^2.0.0
  #  image_picker:
  #    path: ./plugins/image_picker-0.6.5
  orientation: ^1.2.0
  flutter_inapp_purchase:
    path: ./plugins/flutter_inapp_purchase-2.2.0
  #  flutter_webview_plugin: ^0.3.8
  flutter_webview_plugin:
    path: ./plugins/flutter_webview_plugin-0.3.11
  webview_flutter_plus:
    path: ./plugins/webview_flutter_plus-0.1.1+9
  image_cropper: ^1.2.3
  oktoast: ^2.2.0
  fluwx_no_pay: ^2.3.2
#  fluwx: ^2.2.0
#  fluwx:
#    path: ./plugins/fluwx
  flick_video_player: ^0.1.1
  liquid_progress_indicator: ^0.3.2
  # websocket_manager: ^0.2.2
  better_socket:
    path: ./plugins/better_socket-1.1.4
  fradio: ^1.0.1
  fsuper: ^2.0.1
  frefresh: ^1.1.0
  floading: ^1.0.2
  home_indicator: ^1.1.5
  device_info:
    path: ./plugins/device_info
  #  webview_flutter:
  #    path: ./plugins/webview_flutter
  flutter_native_image:
    path: ./plugins/flutter_native_image
  tencent_cos:
    path: ./plugins/tencent_cos
  #直播
  yondor_whiteboard:
    path: ./plugins/yondor_whiteboard
  agora_rtm: ^0.9.12
  provider: ^4.1.3
#  agora_rtc_engine: ^3.2.1
  agora_rtc_engine:
    path: ./plugins/agora_rtc_engine-1.0.15
  archive: ^2.0.13
  bessel_tween: ^0.1.0
  simple_animations: ^2.2.1
  sa_multi_tween: ^1.1.1
  just_audio: ^0.3.3
  screen: ^0.0.5
  fijkplayer: ^0.8.7
  process: ^3.0.13
  socket_io_client: ^0.9.11
#  flutter_vlc_player: ^3.0.7
#  flutter_tencentplayer: ^0.10.0
  flutter_localizations:
    sdk: flutter

#  x5_webview: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  #json_model: #flutter packages pub run json_model
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/model.tflite
    - images/mall_home_commend_default_avater.png
    - images/btn-close.png
    - images/home/
    - images/phone_login/
    - images/admin/
    - images/register/
    - images/coach/
    - images/study/
    - images/eye/
    - images/parent_reward/
    - images/live/
    - images/live/top/
    - images/live/rank/
    - images/update/ic_up_bg.png
    - images/update/ic_update_bg.png
    - images/update/ic_up_close.png
    - images/share/pyqShare.png
    - images/share/xwShare.png
    - images/ic_hand_down.png
    - images/ic_hand_up.png
    - images/ic_student.png
    - images/ic_teacher.png
    - images/live/chat/
    - assets/sounds/star.mp3
    - assets/sounds/ready_go.mp3
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
